
// Indices into spr_Mugshots
enum Mugshot {
  NONE = -1,
  RAVENMAN = 0,
  BRICKMAN = 1,
  RAVENBOY = 2,
  RAVENGIRL_INTRO = 3,
  RAVENGIRL = 4,
  BRICKMAN_DISGUISED = 5,
  MINIONMAN = 6,
  BARRY = 7,
  ICOSAKING = 8,
  DOCTOR = 9,
  CLOWN = 10,
  MAXWELL = 11,
  MILKMAN = 12,
  COUNT = 13,
  BRISTLEGAZE = 14,
  VENOMATRIX = 15,
  CHARMER = 16,
}
