
#macro CARD_WIDTH 302
#macro CARD_HEIGHT 386

#macro EVIL_POINTS_ICON_INDEX 0
#macro FORT_ICON_INDEX 17
#macro CARDS_ICON_INDEX 18

#macro CARD_BACK_INDEX 4
#macro CARD_BLANK_INDEX 5

#macro COLOR_UI_GRAY $999999

#macro DEFAULT_HAND_LIMIT 5
#macro DEFAULT_CARDS_PER_TURN 3

#macro STARTING_EVIL_POINTS_PER_TURN 2
#macro ENDING_EVIL_POINTS_PER_TURN 8
